### ISSUE TITLE
libfdk-aac i686 is missing for Fedora 34

### ISSUE THREAD

**Issue by jp7677** [negativo17/libfdk-aac#1]
Hi there,

I'm currently seeing the following output when running `dnf update` on Fedora 34:

```
Problem: package libfdk-aac-1:2.0.1-1.fc34.x86_64 obsoletes fdk-aac-free < 1:2.0.1-1.fc34 provided by fdk-aac-free-2.0.0-6.fc34.i686
  - cannot install the best update candidate for package fdk-aac-free-2.0.0-6.fc34.i686
  - cannot install the best update candidate for package fdk-aac-free-2.0.0-6.fc34.x86_64
```

It looks like it wants `libfdk-aac-1:2.0.1-1.fc34.i686`. Looking at https://negativo17.org/repos/multimedia/fedora-34/x86_64/ it is indeed not there, whereas the Fedora 33 repository has it (https://negativo17.org/repos/multimedia/fedora-33/x86_64/).

Assuming that I got it right, it would be cool if you could provide the i686 version also for Fedora 34. Thanks!

**Comment by scaronni** [comment]
Hello! May I ask why you need `libfdk-aac.i686` on an `x86_64` system? I was not planning to ship it.

**Comment by jp7677** [comment]
Actually it is not me  wanting it, but dnf complaining.
Looking into my dnf history, from what I see it goes back to Steam (from `negativo17`). The `steam` package is unfortunately `i686` and pulls certain dependencies, among others `pipewire-i686` with somewhere down the road `fdk-aac-free-i686`.
The `libfdk-aac` wants to obsolete `fdk-aac-free` but fails because I have now due to `steam` both the `x64_86` and `i686` of that package on my system.

**Comment by scaronni** [comment]
Ah right, missed that, Pulseaudio is replaced by Pipewire and Pipewire on Fedora 34 requires FDK-AAC. Package online soon.
Thanks.

**Comment by scaronni** [comment]
I'm enabling it also for EL7/8 i686 just in case.

**Comment by jp7677** [comment]
Thanks a lot, cool!
